id = "hex-light-theme"
name = "Hex Light Theme"
version = "0.0.3"
schema_version = 1
authors = ["Hex <lihex.go@gmail.com>"]
description = "Theme with syntax highlighting for Ayu, Latte and Solarized"
repository = "https://github.com/coghost/light-zed-theme"
